# Generated by Django 3.2.4 on 2024-10-25 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_contact_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date']},
        ),
    ]
